# Generated by Django 4.1.3 on 2022-11-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.worker')),
            ],
            bases=('base.worker',),
        ),
        migrations.CreateModel(
            name='Janitor',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.worker')),
            ],
            bases=('base.worker',),
        ),
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('transportation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.transportation')),
            ],
            bases=('base.transportation',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('transportation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.transportation')),
            ],
            bases=('base.transportation',),
        ),
        migrations.CreateModel(
            name='Vehicle_Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collector')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Trolley_Janitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('janitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.janitor')),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trolley')),
            ],
        ),
        migrations.CreateModel(
            name='MCP_Janitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mcp')),
                ('janitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.janitor')),
            ],
        ),
        migrations.CreateModel(
            name='MCP_Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mcp')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collector')),
            ],
        ),
        migrations.AddField(
            model_name='janitor',
            name='mcps',
            field=models.ManyToManyField(through='base.MCP_Janitor', to='base.mcp'),
        ),
        migrations.AddField(
            model_name='janitor',
            name='trolleys',
            field=models.ManyToManyField(through='base.Trolley_Janitor', to='base.trolley'),
        ),
        migrations.AddField(
            model_name='collector',
            name='mcps',
            field=models.ManyToManyField(through='base.MCP_Collector', to='base.mcp'),
        ),
        migrations.AddField(
            model_name='collector',
            name='vehicles',
            field=models.ManyToManyField(through='base.Vehicle_Collector', to='base.vehicle'),
        ),
    ]
