# Generated by Django 4.1.3 on 2022-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_mcp_janitor_mcp_janitor_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcp_janitor',
            options={'ordering': ['work_date']},
        ),
    ]
