# Generated by Django 4.1.3 on 2022-11-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mcp',
            name='location',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='Area_Janitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.area')),
                ('janitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.janitor')),
            ],
            options={
                'ordering': ['work_date'],
            },
        ),
        migrations.AddField(
            model_name='janitor',
            name='areas',
            field=models.ManyToManyField(through='base.Area_Janitor', to='base.area'),
        ),
        migrations.AddConstraint(
            model_name='area_janitor',
            constraint=models.UniqueConstraint(fields=('janitor', 'work_date'), name='area_janitor_date'),
        ),
    ]
