# Generated by Django 4.1.3 on 2022-11-20 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_area_mcp_location_area_janitor_janitor_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcp_collector',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
