# Generated by Django 4.1.3 on 2022-11-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_chatmessage_options_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
